// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrganicFertilizerRecomondation.Models;

namespace OrganicFertilizerRecomondation.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("OrganicFertilizerRecomondation.Models.CropAge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CropTypeId")
                        .HasColumnType("int");

                    b.Property<double>("Nitrigion")
                        .HasColumnType("float");

                    b.Property<double>("Phosphurus")
                        .HasColumnType("float");

                    b.Property<double>("Pottasium")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CropTypeId");

                    b.ToTable("CropAges");
                });

            modelBuilder.Entity("OrganicFertilizerRecomondation.Models.CropType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CropTypes");
                });

            modelBuilder.Entity("OrganicFertilizerRecomondation.Models.NaturalSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("Nitrigion")
                        .HasColumnType("float");

                    b.Property<double>("Phosphurus")
                        .HasColumnType("float");

                    b.Property<double>("Pottasium")
                        .HasColumnType("float");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NaturalSources");
                });

            modelBuilder.Entity("OrganicFertilizerRecomondation.Models.CropAge", b =>
                {
                    b.HasOne("OrganicFertilizerRecomondation.Models.CropType", "CropType")
                        .WithMany()
                        .HasForeignKey("CropTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CropType");
                });
#pragma warning restore 612, 618
        }
    }
}
